# name of the current project, e.g. used for filenames
# in pipeline stages that are run on all project samples at once
project_name: Benchmarking_ProSolo_Hoell2014
# steps to be taken in pipeline stages, specified by file name infixes,
# comment out the lines of stages you don't need, adjust others to your needs
stages:
  preprocessing: .cutadaptIllumina.trimmomaticQual
  mapping: .bwamem
  bam_proc_per_run: .MarkDup
  bam_proc_per_sample: .realigned.recalibrated
  variant_calling: .gatk
folders:
  # The folder where your data can be found, it should be an absolute path.
  data: /path/to/Benchmarking_ProSolo/Hoell2014/data
  # The tmp folder should be set for your SERVER ENVIRONMENT
  tmp: /path/to/tmp
### REFERENCE DATASETS
references:
  # Where to find the reference genome in your SERVER ENVIRONMENT
  hg19: /path/to/refdata/HomoSapiens/GATKResourceBundle-2.8/bwa-0.7.15/ucsc.hg19.fasta
  ground_truth: " "
  # Where to find the set of human chromosomes you look at in your SERVER ENVIRONMENT, only
  # uncomment and adjust if you want to go beyond the canonical chromosomes
#  chromosomes: /path/to/refdata/HomoSapiens/hg19_CanonicalChromosomes
# GATK Bundle files needed for various GATK tools, mostly HaplotypeCaller, this should be set for
# your SERVER ENVIRONMENT (may be deleted if GATK is not used or not used on human data)
GATKBundle:
  # from 2013, 2.8 is still the standard GATK Bundle -- a new one is in the
  # GATK repository at: ftp://ftp.broadinstitute.org/bundle/hg38/hg38bundle/ (TODO)
  '2.8': # quotes are needed, so this is parsed as a string key
    # folder containing the current GATKBundle
    folder: /path/to/refdata/HomoSapiens/GATKResourceBundle-2.8/
    dbsnp: dbsnp_138.hg19.vcf
    g1k: 1000G_phase1.snps.high_confidence.hg19.sites.vcf
    hapmap: hapmap_3.3.hg19.sites.vcf
    mills: Mills_and_1000G_gold_standard.indels.hg19.sites.vcf
    omni: 1000G_omni2.5.hg19.sites.vcf
### OVERRIDING OR AMENDING RULE DEFAULTS
# * 'misc' or 'params' and only string for a tool will AMEND rule defaults
# * other keys will usually override defaults, thus only uncomment and edit them, if
#   the rule defaults don't work for your current dataset
settings:
  bwa_mem: ''
  # Where to find the files annotating your target capture sites, this needs to reflect your
  # SERVER ENVIRONMENT
  capture: /path/to/refdata/HomoSapiens/GATKResourceBundle-2.8/capture
  # These are needed for cutadapt (as these parameters should be tailored to
  # each project, they should be specified in the config file, but good
  # defaults are provided below)
  cutadapt:
    # how many times to look for left-overs of adapter sequence
#    times: ' --times=2 '
    # how many bases of overlap are needed for trimming
#    overlap: ' --overlap=6 '
    # remove all reads with a minimum length lower than n in:
    # --minimum-length=n
    # if another round of trimming, e.g. with trimmomatic, is performed, leave
    # that filtering to the second tool
#    minlen: ' '
    # cut a fixed amount of bases from front/end of each read with:
    # -u x   -u -y    -U x   -U -y
    # (x bases off of front, y bases off of end of read, u is 1st read, U is 2nd read)
    ## the following is needed only for PAG10 but done to all for consistency
    crop: ' '
    # other command line options to be passed to cutadapt
    misc: ' '
    ## the following adapter additions are needed for PNG
    adapters:
      # additional adapters to look for in the first read (on top of standard Illumina)
      first: ' -a GATCGGAA '
                 #-g ^GATCGGAAGAGCACACGTCT '
             # 1st: Illumina Read2 primer site leftovers, anchored at read start
      # additional adapters to look for in the second read (on top of standard Illumina)
      second: ' ' #' -A TAGATC$ '
              # 1st: Illumina leftovers, anchored at read end
  # These are needed for trimmomatic (as these parameters should be tailored to
  # each project, they should be specified in the config file, but good
  # defaults are provided below)
  trimmomatic:
    # where to find Illumina adapters and how to cut them -- but cutadapt is better at
    # cutting adapters, thus rather use the rules not cutting adapters -- otherwise,
    # use TruSeq3-PE-2.fa for all Illumina data (including single end), as
    # it contains reverse complements of adapters, which helps remove remains
    # of adapter dimer contamination, adjust to your ENVIRONMENT
#    Illumina: ' ILLUMINACLIP:/net/programs/Debian-7-x86_64/Trimmomatic-0.33/adapters/TruSeq3-PE-2.fa:2:30:5:4:true '
    # use "HEADCROP:n" to cut off n bases off the start of the read and use
    # "CROP:n" to trim the read to a length of n, cutting bases off the end
#    crop: ' HEADCROP:2 CROP:95 '
    # remove all reads with a minimum length lower than this value
    minlen: ' MINLEN:25 '
    # parameters for the quality trimming
#    quality: ' SLIDINGWINDOW:4:30 LEADING:20 TRAILING:20 ' # this is the default set in rules/preprocessing/trimming.rules
  polymutt: '' # use for custom options to be passed to rules polymutt or polymutt_denovo
  gatk:
    GenotypeGVCFs: ' --max_alternate_alleles 8 '
    HaplotypeCaller: ' '
    bamOutput: 'False'
    # Where to find the set of chromosomes you look at in your ENVIRONMENT
    chromosomes: /path/to/refdata/HomoSapiens/GATKResourceBundle-2.8/chrlist/hg19.CanonicalChromosomes.chr
    heterozygosity: '0.001'
    indel_heterozygosity: '1.25E-4'
    params: ' '
# sequencing read filenames infixes
infix:
  # filename infix for paired end sequencing read files
  pair:
  - '.1'
  - '.2'
  # filename infix for single end sequencing read files
  single:
  - '.0'
### SETUP OF RUNS, SAMPLES AND SAMPLE SETS (BATCHES), INCLUDING ANNOTATION
# a list of sequencing runs and an indication whether the data is paired or
# single end data
runs:
  CCS_1_W: pair
  CCS_2_M: pair
  CCS_3_W: pair
  CCS_4_M: pair
  CCS_5_W: pair
  CCS_6_M: pair
# DNA samples that were sequenced. The same material can be sequenced across
# several runs, that are specified here
samples:
  CCS_1_W:
  - CCS_1_W
  CCS_2_M:
  - CCS_2_M
  CCS_3_W:
  - CCS_3_W
  CCS_4_M:
  - CCS_4_M
  CCS_5_W:
  - CCS_5_W
  CCS_6_M:
  - CCS_6_M
# define batches (sets of samples), if you want to do something per batch (e.g. variant calling)
batches:
  family:
  - CCS_1_W
  - CCS_2_M
  - CCS_3_W
  - CCS_4_M
  - CCS_5_W
  - CCS_6_M
# annotations for the samples, e.g. about DNA material preparation
# the 'platform' is e.g. necessary for bwa mapping
sample_annotations:
  Benchmarking_ProSolo_Hoell2014:
    amplification: none
    library_prep: WX
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  CCS_1_W:
    amplification: none
    library_prep: WX
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  CCS_2_M:
    amplification: none
    library_prep: WX
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  CCS_3_W:
    amplification: none
    library_prep: WX
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  CCS_4_M:
    amplification: none
    library_prep: WX
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  CCS_5_W:
    amplification: none
    library_prep: WX
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  CCS_6_M:
    amplification: none
    library_prep: WX
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA

