# name of the current project, e.g. used for filenames
# in pipeline stages that are run on all project samples at once
project_name: Benchmarking_ProSolo_Wang2014
data_set: Wang2014
# steps to be taken in pipeline stages, specified by file name infixes,
# comment out the lines of stages you don't need, adjust others to your needs
stages:
  preprocessing: .cutadaptIllumina.trimmomaticQual
  mapping: .bwamem
  bam_proc_per_run: .MarkDup_SE
  bam_proc_per_sample: ''
folders:
  # The folder where your data can be found, it should be an absolute path.
  data: /path/to/Wang2014/data
  # The tmp folder should be set for your SERVER ENVIRONMENT
  tmp: /tmp/nobackup/user/tmp
### REFERENCE DATASETS
references:
  # Where to find the reference genome in your SERVER ENVIRONMENT
  hg19: /path/to/refdata/HomoSapiens/hg19_CanonicalChr/genome_bwa-0.7.9a/hg19.fa
  ground_truth: variant_calling/hg19/TNBC-Pop-Normal.bulk.ground_truth.tsv.gz
  normal_ground_truth: variant_calling/hg19/TNBC-Pop-Normal.bulk.ground_truth.somatics_added.tsv.gz
  tumor_ground_truth: variant_calling/hg19/TNBC-Pop-Tumor.bulk.ground_truth.somatics_removed.tsv.gz
  somatic: somatic_validated_mutations/Wang2014_ground_truth_non_synonymous_variants.hg18_to_hg19.tsv
  ground_truth_minGQ_30: variant_calling/hg19/TNBC-Pop-Normal.bulk.ground_truth.minGQ_30.tsv.gz
  ground_truth_bcf: ''
  shapeit_folder: /path/to/refdata/HomoSapiens/hg19_shapeit/1000GP_Phase3
  # Where to find the set of human chromosomes you look at in your SERVER ENVIRONMENT, only
  # uncomment and adjust if you want to go beyond the canonical chromosomes
#  chromosomes: /vol/cluster-data/dlaehnem/refdata/HomoSapiens/hg19_CanonicalChromosomes
# GATK Bundle files needed for various GATK tools, mostly HaplotypeCaller, this should be set for
# your SERVER ENVIRONMENT (may be deleted if GATK is not used or not used on human data)
GATKBundle:
  # from 2013, 2.8 is still the standard GATK Bundle -- a new one is in the
  # GATK repository at: ftp://ftp.broadinstitute.org/bundle/hg38/hg38bundle/ (TODO)
  '2.8': # quotes are needed, so this is parsed as a string key
    # folder containing the current GATKBundle
    folder: /path/to/refdata/HomoSapiens/hg19_GATKBundle-2.8/
    dbsnp: dbsnp_138.hg19.vcf
    g1k: 1000G_phase1.snps.high_confidence.hg19.vcf
    hapmap: hapmap_3.3.hg19.vcf
    mills: Mills_and_1000G_gold_standard.indels.hg19.vcf
    omni: 1000G_omni2.5.hg19.vcf
### OVERRIDING OR AMENDING RULE DEFAULTS
# * 'misc' or 'params' and only string for a tool will AMEND rule defaults
# * other keys will usually override defaults, thus only uncomment and edit them, if
#   the rule defaults don't work for your current dataset
settings:
  bwa_mem: ''
  # Where to find the files annotating your target capture sites, this needs to reflect your
  # SERVER ENVIRONMENT
  # These are needed for cutadapt (as these parameters should be tailored to
  # each project, they should be specified in the config file, but good
  # defaults are provided below)
  capture: '/path/to/refdata/HomoSapiens/hg19/annotation/capture'
  cutadapt:
    # how many times to look for left-overs of adapter sequence
#    times: ' --times=2 '
    # how many bases of overlap are needed for trimming
#    overlap: ' --overlap=6 '
    # remove all reads with a minimum length lower than n in:
    # --minimum-length=n
    # if another round of trimming, e.g. with trimmomatic, is performed, leave
    # that filtering to the second tool
#    minlen: ' '
    # cut a fixed amount of bases from front/end of each read with:
    # -u x   -u -y    -U x   -U -y
    # (x bases off of front, y bases off of end of read, u is 1st read, U is 2nd read)
    ## the following is needed only for PAG10 but done to all for consistency
    crop: ' -u -1 '
    # other command line options to be passed to cutadapt
    misc: ' '
    ## the following adapter additions are needed for PNG
    adapters:
      # additional adapters to look for in the first read (on top of standard Illumina)
      first: ' -b CTGTCTCTTATACACATCT -a AGATCGGAAGAG ' # Nextera Adapter Triming sequence and Illumina Universal Adapter
  # These are needed for trimmomatic (as these parameters should be tailored to
  # each project, they should be specified in the config file, but good
  # defaults are provided below)
  trimmomatic:
    # where to find Illumina adapters and how to cut them -- but cutadapt is better at
    # cutting adapters, thus rather use the rules not cutting adapters -- otherwise,
    # use TruSeq3-PE-2.fa for all Illumina data (including single end), as
    # it contains reverse complements of adapters, which helps remove remains
    # of adapter dimer contamination, adjust to your ENVIRONMENT
#    Illumina: ' ILLUMINACLIP:/net/programs/Debian-7-x86_64/Trimmomatic-0.33/adapters/TruSeq3-PE-2.fa:2:30:5:4:true '
    # use "HEADCROP:n" to cut off n bases off the start of the read and use
    # "CROP:n" to trim the read to a length of n, cutting bases off the end
#    crop: ' HEADCROP:2 CROP:95 '
    # remove all reads with a minimum length lower than this value
    minlen: ' MINLEN:20 '
    # parameters for the quality trimming
    # * standard settings were impossible, almost no data remained (MBs per read file_
    # * SLIDINGWINDOW:4:24 LEADING:18 TRAILING:18 reduced data by more than a third, for IL-12 almost only singletons remained
    quality: ' SLIDINGWINDOW:4:18 LEADING:10 TRAILING:10 '
  gatk:
    GenotypeGVCFs: ' --max_alternate_alleles 8 '
#    HaplotypeCaller: ' '
#    bamOutput: 'True'
    heterozygosity: '0.001'
    indel_heterozygosity: '1.25E-4'
    params: ' '
# sequencing read filenames infixes
infix:
  # filename infix for paired end sequencing read files
  pair:
  - '.1'
  - '.2'
  # filename infix for single end sequencing read files
  single:
  - '.0'
### SETUP OF RUNS, SAMPLES AND SAMPLE SETS (BATCHES), INCLUDING ANNOTATION
# a list of sequencing runs and an indication whether the data is paired or
# single end data
runs:
  SRR1163012: single
  SRR1163013: single
  SRR1163019: single
  SRR1163026: single
  SRR1163027: single
  SRR1163034: single
  SRR1163035: single
  SRR1163043: single
  SRR1163053: single
  SRR1163070: single
  SRR1163074: single
  SRR1163083: single
  SRR1163084: single
  SRR1163091: single
  SRR1163095: single
  SRR1163148: single
  SRR1163149: single
  SRR1163150: single
  SRR1163151: single
  SRR1163152: single
  SRR1163153: single
  SRR1163154: single
  SRR1163155: single
  SRR1163156: single
  SRR1163157: single
  SRR1163158: single
  SRR1163159: single
  SRR1163160: single
  SRR1163161: single
  SRR1163162: single
  SRR1163163: single
  SRR1163164: single
  SRR1163508: single
  SRR1298936: single
# DNA samples that were sequenced. The same material can be sequenced across
# several runs, that are specified here
samples:
  TNBC-Pop-Normal:
  - SRR1163508
  TNBC-Pop-Tumor:
  - SRR1298936
  TNBC-n1:
  - SRR1163149
  TNBC-n10:
  - SRR1163158
  TNBC-n11:
  - SRR1163159
  TNBC-n12:
  - SRR1163160
  TNBC-n13:
  - SRR1163161
  TNBC-n14:
  - SRR1163162
  TNBC-n15:
  - SRR1163163
  TNBC-n16:
  - SRR1163164
  TNBC-n2:
  - SRR1163150
  TNBC-n3:
  - SRR1163151
  TNBC-n4:
  - SRR1163152
  TNBC-n5:
  - SRR1163153
  TNBC-n6:
  - SRR1163154
  TNBC-n7:
  - SRR1163155
  TNBC-n8:
  - SRR1163156
  TNBC-n9:
  - SRR1163157
  a1:
  - SRR1163012
  a2:
  - SRR1163013
  a3:
  - SRR1163019
  a4:
  - SRR1163026
  a5:
  - SRR1163027
  a6:
  - SRR1163034
  a7:
  - SRR1163035
  a8:
  - SRR1163043
  h1:
  - SRR1163053
  h2:
  - SRR1163070
  h3:
  - SRR1163074
  h4:
  - SRR1163083
  h5:
  - SRR1163084
  h6:
  - SRR1163091
  h7:
  - SRR1163095
  h8:
  - SRR1163148
# define batches (sets of samples), if you want to do something per batch (e.g. variant calling)
batches:
  ground_truth_bulk:
  - TNBC-Pop-Normal
  bulk:
  - TNBC-Pop-Tumor
  single_cells:
  - a1
  - a2
  - a3
  - a4
  - a5
  - a6
  - a7
  - a8
  - h1
  - h2
  - h3
  - h4
  - h5
  - h6
  - h7
  - h8
  - TNBC-n1
  - TNBC-n2
  - TNBC-n3
  - TNBC-n4
  - TNBC-n5
  - TNBC-n6
  - TNBC-n7
  - TNBC-n8
  - TNBC-n9
  - TNBC-n10
  - TNBC-n11
  - TNBC-n12
  - TNBC-n13
  - TNBC-n14
  - TNBC-n15
  - TNBC-n16
  tumor_cells:
  - a1
  - a2
  - a3
  - a4
  - a5
  - a6
  - a7
  - a8
  - h1
  - h2
  - h3
  - h4
  - h5
  - h6
  - h7
  - h8
  normal_cells:
  - TNBC-n1
  - TNBC-n2
  - TNBC-n3
  - TNBC-n4
  - TNBC-n5
  - TNBC-n6
  - TNBC-n7
  - TNBC-n8
  - TNBC-n9
  - TNBC-n10
  - TNBC-n11
  - TNBC-n12
  - TNBC-n13
  - TNBC-n14
  - TNBC-n15
  - TNBC-n16
# annotations for the samples, e.g. about DNA material preparation
# the 'platform' is e.g. necessary for bwa mapping
sample_annotations:
  TNBC-Pop-Normal:
    amplification: none
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  TNBC-Pop-Tumor:
    amplification: none
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  TNBC-n1:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  TNBC-n10:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  TNBC-n11:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  TNBC-n12:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  TNBC-n13:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  TNBC-n14:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  TNBC-n15:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  TNBC-n16:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  TNBC-n2:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  TNBC-n3:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  TNBC-n4:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  TNBC-n5:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  TNBC-n6:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  TNBC-n7:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  TNBC-n8:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  TNBC-n9:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  a1:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  a2:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  a3:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  a4:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  a5:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  a6:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  a7:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  a8:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  h1:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  h2:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  h3:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  h4:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  h5:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  h6:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  h7:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA
  h8:
    amplification: MDA
    library_selection: WXS
    library_source: GENOMIC
    machine: Illumina HiSeq 2000
    platform: ILLUMINA

